spring.datasource.url=jdbc:sqlite:washie.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Disable Spring Boot banner and web server
spring.main.web-application-type=none
spring.main.banner-mode=off
logging.level.root=WARN
logging.level.com.washie=INFO
